### ISSUE TITLE
Not able to install matrixdriver

### ISSUE THREAD

**Issue by isaacmorph** [hanckmann/matrixdriver#2]
Hi,
When I try to run pip install -r requirements.txt, I get the following error message:
Collecting matrixdriver==0.9.0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement matrixdriver==0.9.0 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for matrixdriver==0.9.0 (from -r requirements.txt (line 1))

Any ideas?
Regards,
Roger

PS I made a change in my local copy of requirements.txt; from matrixdriver=0.9.0 to matrixdriver==0.9.0 DS

**Comment by hanckmann** [comment]
Oke, so somehow I included this library itself in the requirements.txt
So I removed it from the file and it should work now.
