### ISSUE TITLE
Setting up and use it

### ISSUE THREAD

**Issue by Gualberto-Vannini** [hanckmann/matrixdriver#4]
I can't setting up and use properly matrixdriver. Can anyone explain me much better all the passages?

I used in my Raspberry Pi3 modelB:

`$ git clone https://github.com/hanckmann/matrixdriver.git`
`$ cd matrixdriver `
`$ pip install -r requirements.txt`
`$ cd driver`
`$ sudo python3 setup.py install`
`$ cd ..`
`$ python3 imagedriver.py `

and I get this:

![schermata 2018-08-24 alle 17 38 51](https://user-images.githubusercontent.com/22340454/44593815-beb8a280-a7c4-11e8-9cb0-a8dfbe68ab92.png)

Can Someone help me with this problem to test "8x8 RPI-RGB-LED-Matrix based on the 74HC595 chip"

**Comment by hanckmann** [comment]
This package requires to be installed to be able to work. You can install it like any (other) standard python package:

pip install matrixdriver

Also https://pypi.org/project/matrixdriver/

You have downloaded the (open source) source code.
